### PR TITLE
Cleaning up local tasks

### PR DESCRIPTION
**Pull request by pcambra**

### CODE REVIEW

**Comment by bojanz** [comment]
It feels really odd that we're bypassing the entity api for profile types, and loading them from config directly. Why is that?

**Comment by pcambra** [comment]
I was thinking about it myself... it was what it was there before, I honestly don't have very clear if it makes a big difference. I can use entity manager instead.

**Comment by pcambra** [comment]
Also, I'm facing the issue that the tabs don't appear until you clear the cache for the first time. Need to check that better.

**Comment by bojanz** [comment]
Yeah let's just use the EntityTypeManager to get the profile_type storage and load profile types (remember, entityManager is deprecated).

**Comment by bojanz** [comment]
I learned something new today:
 \Drupal::service('entity_type.bundle.info')->getBundleInfo('profile');
This gets all bundles of the profile entity type. Has its own cache, and seems to be core's preferred way of getting the list of bundles.

**Comment by bojanz** [comment]
Committed as 98c3c62c44dad26d96bf3bdbdf4053e2249144a7

**Pull request closed without merging**
