### PR TITLE
Replace deprecated entity functions

### PR DESCRIPTION
**Pull request by GoZOo**
Many deprecated entity functions are still used. So i replace them.

* entity_load_multiple_by_properties()
* entity_create()
* entity_get_display()
* entity_get_form_display()
* DRUPAL_AUTHENTICATED_RID constant
* direct access to object properties in tests and not get().

### CODE REVIEW

**Comment by bojanz** [comment]
Needs a rebase.

Assign the storage to a variable if it's reused in the same method, don't do getStorage() for the same entity type multiple times.

**Comment by GoZOo** [comment]
Rebase is ok and use one variable for same storages.

**Comment by bojanz** [comment]
$storage_profile should be $profile_storage, same for others.

\Drupal::entityManager() is deprecated, we need to use \Drupal::service('entity_type.manager') instead.

**Comment by GoZOo** [comment]
I miss this one ! I'll check this

**Comment by bojanz** [comment]
Continued in #15

**Pull request closed without merging**
